server:
  port: 10231
book:
  name: 'Three-body'
  author: 'LIU'

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://sit-mysql8.cttvfwmppwab.rds.cn-northwest-1.amazonaws.com.cn:3306/pretend_dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
          username: admin
          password: jmjqr123
        slave_1:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://sit-mysql8.cttvfwmppwab.rds.cn-northwest-1.amazonaws.com.cn:3306/pretend_dev2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
          username: admin
          password: jmjqr123
  initialSize: 5    # 初始化大小
  minIdle: 5        # 最小
  maxActive: 20     # 最大
  maxWait: 60000    # 获取连接等待超时的时间
  timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true                    # 打开PSCache
  maxPoolPreparedStatementPerConnectionSize: 20   # 指定每个连接上PSCache的大小
  filters: stat,wall,log4j                        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开
  useCompression: true

mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type:
        - AUTO
      field-strategy:
        - 1
      table-underline:
        - true
      logic-delete-value:
        - 1
      logic-not-delete-value:
        - 0
  configuration:
    map-underscore-to-camel-case:
      - true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true